import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./page";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <nav>
          <Link href={"/"}>Home</Link>&nbsp;&nbsp;
          <Link href={"/posts"}>post</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
